name: google-apps-desktop
version: 2.0.1
summary: A desktop application providing access to all Google apps in one place.
description: |
  Google Apps Desktop provides a seamless experience for accessing Google services like Gmail, Drive, and Calendar in one unified desktop application.
confinement: classic
grade: stable
base: core22  # Use core20 if required for older compatibility
icon: ../assets/icon.png

apps:
  google-apps-desktop:
    command: google-apps-desktop  # Ensure correct binary path
    desktop: google-apps-desktop.desktop  # Reference desktop entry
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - network

parts:
  google-apps-desktop:
    plugin: dump
    source: .
    organize:
      google-apps: google-apps-desktop  # Ensures binary is correctly placed
