name: google-apps-desktop
summary: A desktop application providing access to all Google apps in one place.
description: |
  A desktop application providing access to all Google apps in one place.

grade: stable
confinement: strict

apps:
  gmail-app:
    command: google-apps
    icon: ../assets/icon.png
    productName: Google Apps Desktop